# При виконанні інструкції assert з логічним виразом, результат якого дорівнює True,
# нічого не станеться. Але якщо спробувати виконати інструкцію assert з логічним виразом,
# який дорівнює False, то буде згенеровано виняток AssertionError.
# Винятки AssertionError призначені радше для налагодження — з їх допомогою,
# при написанні програм на етапі розробки ми можемо бачити, що робимо щось не так
# (наприклад, передали в метод некоректне значення). Також не потрібно, наприклад,
# обробляти введення користувача і намагатися обробити виключення AssertionError блоком try-except.
# Якщо у вашому коді буде дуже багато assert'ів, це торкнеться і продуктивності програми.

def get_user_by_id(user_id):
    assert type(user_id) is int, 'user_id must be integer'
    print('Searching...')


get_user_by_id(4267)
# Searching...

get_user_by_id('foo')
# AssertionError: user_id must be integer
