# Якщо під час виконання будь-якої операції з файлом виникає виняток,
# програма завершує виконання, не закриваючи при цьому файли.
# Одним із рішень в цій ситуації є використання блоку try...finally.

try:
    file1 = open("sample.txt", "r")
    read_content = file1.read()
    print(read_content)

finally:
    # Закриваємо файл
    file1.close()
